// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingStrat.Infrastructure.Persistence.EfCore;

#nullable disable

namespace TradingStrat.Infrastructure.Migrations
{
    [DbContext(typeof(TradingContext))]
    [Migration("20251220125956_AddAiAssistantTables")]
    partial class AddAiAssistantTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TradingStrat.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("IX_ChatMessages_Session_Timestamp");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TradingStrat.Domain.Entities.HistoricalPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AdjustedClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ISIN")
                        .HasDatabaseName("IX_HistoricalPrices_ISIN");

                    b.HasIndex("Ticker", "DateTime")
                        .IsUnique()
                        .HasDatabaseName("IX_HistoricalPrices_Ticker_DateTime");

                    b.ToTable("HistoricalPrices");
                });

            modelBuilder.Entity("TradingStrat.Domain.Entities.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISIN")
                        .IsUnique()
                        .HasDatabaseName("IX_Securities_ISIN");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_Securities_Ticker");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("TradingStrat.Domain.Entities.StrategyRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "CreatedAt")
                        .HasDatabaseName("IX_StrategyRecommendations_Ticker_CreatedAt");

                    b.ToTable("StrategyRecommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
