using TradingStrat.Domain.Common;

namespace TradingStrat.Domain.ValueObjects;

/// <summary>
/// Enumeration of possible trading signals generated by strategies.
/// </summary>
public enum SignalType
{
    /// <summary>
    /// No action - maintain current position.
    /// </summary>
    Hold,

    /// <summary>
    /// Buy signal - open or increase a long position.
    /// </summary>
    Buy,

    /// <summary>
    /// Sell signal - close or decrease a position.
    /// </summary>
    Sell
}

/// <summary>
/// Value object representing a trading signal generated by a strategy.
/// Immutable record containing the decision, price, quantity, and reasoning.
/// </summary>
public record TradeSignal
{
    public SignalType Type { get; init; }
    public decimal Price { get; init; }
    public int Quantity { get; init; }
    public string Reason { get; init; } = string.Empty;

    public TradeSignal(SignalType Type, decimal Price, int Quantity, string Reason)
    {
        // Validate price - only required for Buy/Sell signals (Hold can have 0)
        if ((Type == SignalType.Buy || Type == SignalType.Sell) && Price <= 0m)
        {
            throw new ArgumentException($"{Type} signals must have price greater than 0", nameof(Price));
        }

        // Validate reason
        ValidationGuard.Require(Reason).NotNullOrWhiteSpace();

        // Validate quantity based on signal type
        if (Type == SignalType.Hold && Quantity != 0)
        {
            throw new ArgumentException("Hold signals must have quantity of 0", nameof(Quantity));
        }

        if ((Type == SignalType.Buy || Type == SignalType.Sell) && Quantity <= 0)
        {
            throw new ArgumentException($"{Type} signals must have quantity greater than 0", nameof(Quantity));
        }

        this.Type = Type;
        this.Price = Price;
        this.Quantity = Quantity;
        this.Reason = Reason;
    }
};
