using TradingStrat.Domain.Common;

namespace TradingStrat.Domain.ValueObjects;

/// <summary>
/// Enumeration of possible trading signals generated by strategies.
/// </summary>
public enum SignalType
{
    /// <summary>
    /// No action - maintain current position.
    /// </summary>
    Hold,

    /// <summary>
    /// Buy signal - open or increase a long position.
    /// </summary>
    Buy,

    /// <summary>
    /// Sell signal - close or decrease a position.
    /// </summary>
    Sell
}

/// <summary>
/// Value object representing a trading signal generated by a strategy.
/// Immutable record containing the decision, price, quantity, and reasoning.
/// </summary>
public sealed class TradeSignal : ValueObject
{
    public SignalType Type { get; init; }
    public decimal Price { get; init; }
    public int Quantity { get; init; }
    public string Reason { get; init; } = string.Empty;

    public TradeSignal(SignalType type, decimal price, int quantity, string reason)
    {
        // Validate price - only required for Buy/Sell signals (Hold can have 0)
        if ((type == SignalType.Buy || type == SignalType.Sell) && price <= 0m)
        {
            throw new ArgumentException($"{type} signals must have price greater than 0", nameof(price));
        }

        // Validate reason
        ValidationGuard.Require(reason).NotNullOrWhiteSpace();

        // Validate quantity based on signal type
        if (type == SignalType.Hold && quantity != 0)
        {
            throw new ArgumentException("Hold signals must have quantity of 0", nameof(quantity));
        }

        if ((type == SignalType.Buy || type == SignalType.Sell) && quantity <= 0)
        {
            throw new ArgumentException($"{type} signals must have quantity greater than 0", nameof(quantity));
        }

        Type = type;
        Price = price;
        Quantity = quantity;
        Reason = reason;
    }

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Type;
        yield return Price;
        yield return Quantity;
        yield return Reason;
    }
}
