namespace TradingStrat.Domain.ValueObjects;

/// <summary>
/// Enumeration of possible trading signals generated by strategies.
/// </summary>
public enum SignalType
{
    /// <summary>
    /// No action - maintain current position.
    /// </summary>
    Hold,

    /// <summary>
    /// Buy signal - open or increase a long position.
    /// </summary>
    Buy,

    /// <summary>
    /// Sell signal - close or decrease a position.
    /// </summary>
    Sell
}

/// <summary>
/// Value object representing a trading signal generated by a strategy.
/// Immutable record containing the decision, price, quantity, and reasoning.
/// </summary>
/// <param name="Type">Type of signal (Buy, Sell, or Hold).</param>
/// <param name="Price">Price at which the signal was generated.</param>
/// <param name="Quantity">Number of shares to trade (0 for Hold signals).</param>
/// <param name="Reason">Human-readable explanation of why this signal was generated.</param>
public record TradeSignal(
    SignalType Type,
    decimal Price,
    int Quantity,
    string Reason
);
