// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBot.Infrastructure.Persistence;

#nullable disable

namespace TradingBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingBotDbContext))]
    [Migration("20251107200434_AddUserPreferences")]
    partial class AddUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TradingBot.Core.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomSettings")
                        .HasColumnType("TEXT");

                    b.Property<int>("DashboardRefreshInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowErrorNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInfoNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowSuccessNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowWarningNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.MarketData.Candle", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("timeframe");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("open");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "Timestamp", "Timeframe");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_candles_symbol");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_candles_timestamp");

                    b.HasIndex("Symbol", "Timeframe")
                        .HasDatabaseName("idx_candles_symbol_timeframe");

                    b.ToTable("candles", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.MarketData.Quote", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Ask")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("bid");

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("change");

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("change_percent");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "Timestamp");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_quotes_symbol");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_quotes_timestamp");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.Portfolio.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<decimal>("BuyingPower")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("buying_power");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash");

                    b.Property<decimal>("Equity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("equity");

                    b.Property<decimal>("Leverage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m)
                        .HasColumnName("leverage");

                    b.Property<decimal>("PositionValue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("position_value");

                    b.Property<decimal>("RealizedPnL")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("realized_pnl");

                    b.Property<decimal>("UnrealizedPnL")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("unrealized_pnl");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.Portfolio.EquityPoint", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("CumulativeReturn")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("cumulative_return");

                    b.Property<decimal>("Equity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("equity");

                    b.HasKey("Timestamp");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_equity_points_timestamp");

                    b.ToTable("equity_points", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.Trading.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageFillPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_fill_price");

                    b.Property<decimal>("Commission")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("commission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("filled_at");

                    b.Property<decimal>("FilledQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("filled_quantity");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("limit_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal?>("StopPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_price");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_name");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_orders_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.HasIndex("StrategyName")
                        .HasDatabaseName("idx_orders_strategy");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_orders_symbol");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.Trading.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_price");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_price");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_loss");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("take_profit");

                    b.HasKey("Id");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("idx_positions_opened_at");

                    b.HasIndex("StrategyName")
                        .HasDatabaseName("idx_positions_strategy");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_positions_symbol");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradingBot.Core.Models.Trading.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Commission")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("commission");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_price");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_time");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("exit_price");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("exit_time");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("EntryTime")
                        .HasDatabaseName("idx_trades_entry_time");

                    b.HasIndex("ExitTime")
                        .HasDatabaseName("idx_trades_exit_time");

                    b.HasIndex("StrategyName")
                        .HasDatabaseName("idx_trades_strategy");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_trades_symbol");

                    b.ToTable("trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
