// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradyStrat.Infrastructure.Data;

#nullable disable

namespace TradyStrat.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522140532_AddCitationsTable")]
    partial class AddCitationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TradyStrat.Domain.FxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Base", "Quote", "Date")
                        .IsUnique();

                    b.ToTable("FxRates", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.GoalConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetEur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Trade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExecutedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedOn");

                    b.HasIndex("PositionId");

                    b.HasIndex("InstrumentId", "ExecutedOn");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.PriceBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Date")
                        .IsUnique();

                    b.ToTable("PriceBars", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.SettingEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Suggestions.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitationsJson")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("Conviction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ForDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT")
                        .HasColumnName("MarketSnapshotJson");

                    b.Property<string>("ThinkingText")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ForDate", "InstrumentId")
                        .IsUnique();

                    b.ToTable("Suggestions", (string)null);
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Position", b =>
                {
                    b.HasOne("TradyStrat.Domain.Portfolio.Portfolio", null)
                        .WithMany("_positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("TradyStrat.Domain.Portfolio.Lot", "_openLots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("OpenedOn")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PositionId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("PositionId");

                            b1.ToTable("PositionLots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");

                            b1.OwnsOne("TradyStrat.Domain.Shared.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<int>("LotId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsSpecified")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("QuantityIsSpecified");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Quantity");

                                    b2.HasKey("LotId");

                                    b2.ToTable("PositionLots");

                                    b2.WithOwner()
                                        .HasForeignKey("LotId");
                                });

                            b1.OwnsOne("TradyStrat.Domain.Shared.Money", "UnitCost", b2 =>
                                {
                                    b2.Property<int>("LotId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("UnitCostAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("UnitCostCurrency");

                                    b2.Property<bool>("IsEmpty")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("UnitCostIsEmpty");

                                    b2.HasKey("LotId");

                                    b2.ToTable("PositionLots");

                                    b2.WithOwner()
                                        .HasForeignKey("LotId");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();

                            b1.Navigation("UnitCost")
                                .IsRequired();
                        });

                    b.OwnsOne("TradyStrat.Domain.Shared.Money", "_realizedPnL", b1 =>
                        {
                            b1.Property<int>("PositionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("RealizedPnLAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("RealizedPnLCurrency");

                            b1.Property<bool>("IsEmpty")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RealizedPnLIsEmpty");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("_openLots");

                    b.Navigation("_realizedPnL");
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Trade", b =>
                {
                    b.HasOne("TradyStrat.Domain.Portfolio.Position", null)
                        .WithMany("_trades")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TradyStrat.Domain.Shared.Money", "Fees", b1 =>
                        {
                            b1.Property<int>("TradeId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("FeesAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("FeesCurrency");

                            b1.Property<bool>("IsEmpty")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FeesIsEmpty");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("TradyStrat.Domain.Shared.Price", "PricePerShare", b1 =>
                        {
                            b1.Property<int>("TradeId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");

                            b1.OwnsOne("TradyStrat.Domain.Shared.Money", "PerUnit", b2 =>
                                {
                                    b2.Property<int>("PriceTradeId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PricePerShareAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PricePerShareCurrency");

                                    b2.Property<bool>("IsEmpty")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("PricePerShareIsEmpty");

                                    b2.HasKey("PriceTradeId");

                                    b2.ToTable("Trades");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceTradeId");
                                });

                            b1.Navigation("PerUnit")
                                .IsRequired();
                        });

                    b.OwnsOne("TradyStrat.Domain.Shared.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<int>("TradeId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSpecified")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityIsSpecified");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Quantity");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("PricePerShare")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("TradyStrat.Domain.Suggestions.Suggestion", b =>
                {
                    b.OwnsMany("TradyStrat.Domain.Suggestions.Citation", "Citations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Claim")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Indicator")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<int>("SuggestionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Ticker")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SuggestionId");

                            b1.ToTable("Citations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SuggestionId");
                        });

                    b.OwnsOne("TradyStrat.Domain.Suggestions.PromptFingerprint", "Fingerprint", b1 =>
                        {
                            b1.Property<int>("SuggestionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("EnvelopeHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnvelopeHash");

                            b1.Property<string>("PromptHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("PromptHash");

                            b1.Property<string>("PromptVersionHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("PromptVersionHash");

                            b1.HasKey("SuggestionId");

                            b1.ToTable("Suggestions");

                            b1.WithOwner()
                                .HasForeignKey("SuggestionId");
                        });

                    b.OwnsOne("TradyStrat.Domain.Shared.Price", "MaxPriceHint", b1 =>
                        {
                            b1.Property<int>("SuggestionId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SuggestionId");

                            b1.ToTable("Suggestions");

                            b1.WithOwner()
                                .HasForeignKey("SuggestionId");

                            b1.OwnsOne("TradyStrat.Domain.Shared.Money", "PerUnit", b2 =>
                                {
                                    b2.Property<int>("PriceSuggestionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MaxPriceHint");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MaxPriceHintCurrency");

                                    b2.Property<bool>("IsEmpty")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MaxPriceHintIsEmpty");

                                    b2.HasKey("PriceSuggestionId");

                                    b2.ToTable("Suggestions");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceSuggestionId");
                                });

                            b1.Navigation("PerUnit")
                                .IsRequired();
                        });

                    b.OwnsOne("TradyStrat.Domain.Shared.Quantity", "QuantityHint", b1 =>
                        {
                            b1.Property<int>("SuggestionId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSpecified")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityHintIsSpecified");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("QuantityHint");

                            b1.HasKey("SuggestionId");

                            b1.ToTable("Suggestions");

                            b1.WithOwner()
                                .HasForeignKey("SuggestionId");
                        });

                    b.Navigation("Citations");

                    b.Navigation("Fingerprint")
                        .IsRequired();

                    b.Navigation("MaxPriceHint")
                        .IsRequired();

                    b.Navigation("QuantityHint")
                        .IsRequired();
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Portfolio", b =>
                {
                    b.Navigation("_positions");
                });

            modelBuilder.Entity("TradyStrat.Domain.Portfolio.Position", b =>
                {
                    b.Navigation("_trades");
                });
#pragma warning restore 612, 618
        }
    }
}
