// <copyright file="Signal.cs" company="TradingBot">
// Copyright (c) TradingBot. All rights reserved.
// </copyright>

using TradingBot.Core.Enums;

namespace TradingBot.Core.Models.Trading;

/// <summary>
/// Represents a trading signal generated by a strategy.
/// </summary>
public sealed record Signal
{
    /// <summary>
    /// Gets the unique identifier for this signal.
    /// </summary>
    public required Guid Id { get; init; }

    /// <summary>
    /// Gets the name of the strategy that generated this signal.
    /// </summary>
    public required string StrategyName { get; init; }

    /// <summary>
    /// Gets the trading symbol.
    /// </summary>
    public required string Symbol { get; init; }

    /// <summary>
    /// Gets the type of signal (Buy, Sell, Hold, Close).
    /// </summary>
    public required SignalType Type { get; init; }

    /// <summary>
    /// Gets the timestamp when the signal was generated (UTC).
    /// </summary>
    public required DateTime Timestamp { get; init; }

    /// <summary>
    /// Gets the confidence level of the signal (0.0 to 1.0).
    /// </summary>
    public required decimal Confidence { get; init; }

    /// <summary>
    /// Gets the suggested price for execution.
    /// </summary>
    public decimal? SuggestedPrice { get; init; }

    /// <summary>
    /// Gets optional metadata about the signal (indicators, reasons, etc.).
    /// </summary>
    public IReadOnlyDictionary<string, object>? Metadata { get; init; }
}
